<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>ePonto</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ePonto.ApplicationCore\ePonto.ApplicationCore.csproj" />
    <ProjectReference Include="..\ePonto.Specs.Shared\ePonto.Specs.Shared.csproj" />
  </ItemGroup>

</Project>
